# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\flavi\Desktop\Py files\Accounting Assistant\UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.531, y1:1, x2:0.525584, y2:0, stop:0 rgba(0, 180, 255, 255), stop:0.482955 rgba(70, 92, 124, 255), stop:1 rgba(0, 0, 0, 246));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 220, 241, 131))
        self.frame.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.button_statementWindow = QtWidgets.QPushButton(self.frame)
        self.button_statementWindow.setGeometry(QtCore.QRect(50, 10, 141, 31))
        self.button_statementWindow.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,200);    \n"
"color: rgb(0, 0, 0); \n"
"font: 12pt;\n"
"font-family: \"Microsoft Sans Serif\";\n"
"font-weight: 400;\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover{ \n"
"background-color:rgba(255,255,255,255);\n"
"}")
        self.button_statementWindow.setObjectName("button_statementWindow")
        self.button_stockWindow = QtWidgets.QPushButton(self.frame)
        self.button_stockWindow.setGeometry(QtCore.QRect(50, 50, 141, 31))
        self.button_stockWindow.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,200);    \n"
"color: rgb(0, 0, 0); \n"
"font: 12pt;\n"
"font-family: \"Microsoft Sans Serif\";\n"
"font-weight: 400;\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover{ \n"
"background-color:rgba(255,255,255,255);\n"
"}")
        self.button_stockWindow.setObjectName("button_stockWindow")
        self.button_about = QtWidgets.QPushButton(self.frame)
        self.button_about.setGeometry(QtCore.QRect(50, 90, 141, 31))
        self.button_about.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,200);    \n"
"color: rgb(0, 0, 0); \n"
"font: 12pt;\n"
"font-family: \"Microsoft Sans Serif\";\n"
"font-weight: 400;\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover{ \n"
"background-color:rgba(255,255,255,255);\n"
"}")
        self.button_about.setObjectName("button_about")
        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(570, 430, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_quit.setFont(font)
        self.button_quit.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,200);    \n"
"color: rgb(0, 0, 0); \n"
"font: 12pt;\n"
"font-family: \"Microsoft Sans Serif\";\n"
"font-weight: 400;\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover{ \n"
"background-color:rgba(255,255,255,255);\n"
"}")
        self.button_quit.setObjectName("button_quit")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 50, 431, 111))
        self.frame_2.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_title = QtWidgets.QLabel(self.frame_2)
        self.label_title.setGeometry(QtCore.QRect(80, 20, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(240, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\flavi\\Desktop\\Py files\\Accounting Assistant\\UI\\pngegg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.mainwindow_label = QtWidgets.QLabel(self.frame_2)
        self.mainwindow_label.setGeometry(QtCore.QRect(390, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(50)
        self.mainwindow_label.setFont(font)
        self.mainwindow_label.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(240, 255, 255);\n"
"font-size: 36,")
        self.mainwindow_label.setObjectName("mainwindow_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_statementWindow.setText(_translate("MainWindow", "Processar extrato"))
        self.button_stockWindow.setText(_translate("MainWindow", "Processar NFes"))
        self.button_about.setText(_translate("MainWindow", "Sobre"))
        self.button_quit.setText(_translate("MainWindow", "Sair"))
        self.label_title.setText(_translate("MainWindow", "Accounting Assistant"))
        self.mainwindow_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">v 2.0</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
